export const cities = [
  'Ancona',
  'Bari',
  'Bologna',
  'Brescia',
  'Cagliari',
  'Campobasso',
  'Catania',
  'Catanzaro',
  'Chieti',
  'Ferrara',
  'Firenze',
  'Foggia',
  'Genova',
  'L’Aquila',
  'Messina',
  'Milano',
  'Modena',
  'Napoli',
  'Padova',
  'Palermo',
  'Parma',
  'Pavia',
  'Perugia',
  'Pisa',
  'Roma',
  'Salerno',
  'Sassari',
  'Siena',
  'Torino',
  'Trento',
  'Trieste',
  'Udine',
  'Varese',
  'Vercelli',
  'Verona',
]
export const universities = [
  'Bari',
  'Basilicata (Potenza)',
  'Bologna',
  'Brescia',
  'Cagliari',
  'Catania',
  'Catanzaro',
  'Chieti',
  'Ferrara',
  'Firenze',
  'Foggia',
  'Genova',
  'L’Aquila',
  'Messina',
  'Milano',
  'Milano - Bicocca',
  'Milano - Humanitas University',
  'Milano - San Raffaele',
  'Modena',
  'Molise (Campobasso)',
  'Napoli - Federico II',
  'Napoli - Vanvitelli',
  'Novara - Piemonte Orientale',
  'Padova',
  'Palermo',
  'Parma',
  'Pavia',
  'Perugia',
  'Pisa',
  'Politecnica delle Marche (Ancona)',
  'Roma - La Sapienza',
  'Roma - Tor Vergata',
  'Roma - Campus Biomedico',
  'Roma - Cattolica del sacro cuore',
  'Salerno',
  'Sassari',
  'Siena',
  'Torino',
  'Trento',
  'Trieste',
  'Udine',
  'Varese - Insubria',
  'Verona',
]

export const ssmSubjects = [
  'Allergologia ed immunologia clinica',
  'Anatomia patologica',
  'Anestesia Rianimazione',
  'Audiologia e foniatria',
  'Cardiochirurgia',
  'Chirurgia Generale',
  'Chirurgia maxillo-facciale',
  'Chirurgia pediatrica',
  'Chirurgia plastica, ricostruttiva ed estetica',
  'Chirurgia Toracica',
  'Chirurgia Vascolare',
  'Dermatologia e venereologia',
  'Ematologia',
  'Endocrinologia e malattie del metabolismo',
  'Farmacologia e Tossicologia Clinica',
  'Genetica medica',
  'Geriatria',
  'Ginecologia ed Ostetricia',
  'Igiene e medicina preventiva',
  "Malattie dell'apparato cardiovascolare",
  "Malattie dell'apparato digerente",
  "Malattie dell'apparato respiratorio",
  'Malattie Infettive e Tropicali',
  "Medicina d'emergenza-urgenza",
  'Medicina del lavoro',
  "Medicina dello sport e dell'esercizio fisico",
  'Medicina di comunità e delle cure primarie',
  'Medicina fisica e riabilitativa',
  'Medicina interna',
  'Medicina legale',
  'Medicina nucleare',
  'Medicina termale',
  'Microbiologia e virologia',
  'Nefrologia',
  'Neurochirurgia',
  'Neurologia',
  'Neuropsichiatria infantile',
  'Oftalmologia',
  'Oncologia medica',
  'Ortopedia e traumatologia',
  'Otorinolaringoiatria',
  'Patologia Clinica e Biochimica Clinica',
  'Pediatria',
  'Psichiatria',
  'Radiodiagnostica',
  'Radioterapia',
  'Reumatologia',
  "Scienza dell'alimentazione",
  'Statistica sanitaria e Biometria',
  'Terapia Intensiva e del dolore',
  'Urologia',
]
