export const items = [
  '1 - Semeiotica cardiovascolare',
  '2 - Fattori di rischio cardiovascolare e prevenzione',
  '3 - Cardiopatia ischemica: angina pectoris e infarto del miocardio',
  '4 - Valvulopatie',
  "6 - Patologie dell'aorta (aneurismi e dissezione aortica) e malattie obliteranti dei vasi periferici (AOAI)",
  '7 - Aritmie cardiache',
  '8 - Fibrillazione atriale (FA)',
  '9 - Elettrocardiogramma',
  '10 - Cardiomiopatie',
  '11 - Miocarditi',
  '12 - Ipertensione arteriosa ed emergenze ipertensive',
  '13 - Ipertensione polmonare',
  '14 - Malattie del pericardio: pericardite e versamento pericardico',
  '15 - Scompenso cardiaco ed edema polmonare',
  '17 - Trombosi venosa profonda ed embolia polmonare',
  '18 - Insufficienza venosa cronica e altre patologie delle vene',
  '19 - Endocardite infettiva',
  '20 - Sincope',
  '21 - Valutazione preconcezionale',
  '22 - Farmaci del sistema cardiovascolare',
  '23 - Tumori cardiaci',
  '24 - Aneurisma aortico e malattie obliteranti dei vasi periferici',
  '25 - Dolore toracico acuto e cronico',
  '26 - Trapianto di cuore',
  '31 - Ittero: alterazioni del metabolismo della bilirubina (gilbert) e colestasi croniche (CBP, CSP)',
  '32 - Epatiti virali, autoimmuni e da sostanze tossiche',
  '33 - Epatopatie metaboliche (wilson) ed epatomegalie',
  '34 - Cirrosi epatica e sue complicanze (ascite, ipertensione portale, PBS, encefalopatia epatica, sindrome epatorenale)',
  '35 - Litiasi biliare o colelitiasi e sue complicanze (colecistite, colangite, coledocolitiasi)',
  '36 - Tumori del fegato',
  '37 - Tumori delle vie biliari',
  '38 - Trapianto di fegato',
  "39 - Disfagia, disturbi motori dell'esofago (acalasia), esofagiti",
  '40 - Malattia da reflusso gastroesofageo ed ernia iatale',
  "41 - Tumori dell'esofago",
  '42 - Ulcera gastrica e duodenale. Gastrite acuta e cronica. Gastropatia.',
  '43 - Tumori dello stomaco',
  '44 - Pancreatite acuta',
  '45 - Pancreatite cronica',
  '46 - Tumori pancreatici',
  "47 - Infezioni dell'apparato digerente: enteriti infettive da batteri e virus e parassitosi intestinali: giardiasi, amebiasi, teniasi, ascaridiasi, ossiuriasi",
  "48 - Diarrea non infettiva, diarrea cronica e sindrome dell'intestino irritabile",
  '49 - Disturbi della minzione nei bambini',
  '49 - Stipsi',
  '50 - Malattie Infiammatorie Croniche Intestinali (MICI)',
  '51 - Sindromi da malassorbimento: celiachia, whipple',
  '52 - Malattia diverticolare: diventicolosi e diverticolite',
  '53 - Patologia perianale: emorroidi, ragadi, fistole, incontinenza',
  '54 - Appendicite',
  "55 - Tumori del colon-retto e dell'ano. Poliposi colon-rettali e condizioni eredo familiari predisponenti.",
  '56 - Sanguinamento gastrointestinale',
  '57 - Patologia vascolare intestinale: colite ischemica, ischemia mesenterica',
  '58 - Peritoniti e infezioni addominali',
  '59 - Ascite',
  '60 - Occlusione intestinale (ileo)',
  '61 - Anatomia addominale',
  '62 - Ernie della parete addominale ed inguinali',
  '63 - Vomito',
  '64 - Addome acuto',
  '65 - GIST e NET',
  "66 - Farmaci dell'apparato digerente",
  '71 - Anatomia, fisiologia e semeiotica neurologica',
  '72 - Paralisi facciale',
  '73 - Malattia vascolare cerebrale: TIA, ictus, emorragia intraparenchimale, MAV, trombosi dei seni venosi',
  '74 - Emorragia subdurale, subaracnoidea ed ematoma epidurale',
  '75 - Sclerosi multipla e altre malattie demielinizzanti',
  '76 - Sclerosi laterale amiotrofica e altre malattie del motoneurone',
  '77 - Miastenia e malattie della giunzione neuromuscolare',
  '78 - Neuropatie periferiche: polineuropatie, multineuropatie, poliradiculopatia, plessopatie, ganglionopatia, neuronopatia. Sindromi radicolari, plessuali e dei nervi periferici',
  '79 - Sindrome di Guillain-Barré',
  '80 - Cefalee: emicrania, cefalea muscolotensiva, cefalea autonomica e nevralgia del trigemino. Cefalee secondarie',
  '81 - Deficit motori e/o sensitivi degli arti, Miopatie e distrofie muscolari',
  '82 - Idrocefalo e ipertensione intracranica',
  '83 - Epilessia, crisi epilettiche e sindromi epilettiche. Convulsioni febbrili.',
  "84 - Disturbi della deambulazione e dell'equilibrio",
  '85 - Sindromi da compressione midollare non traumatica: sindrome della cauda equina, siringomielia',
  '86 - Coma e altri disturbi della coscienza. Morte cerebrale',
  '87 - Infezioni del sistema nervoso: meningiti, encefaliti, mieliti , neuriti, radicoliti, ascessi ,empiemi. Tetano e botulino. Malattie da prioni',
  '88 - Disturbi del movimento: Corea di Huntington, Parkinson e Parkinsonismi, Atassie e altri disturbi del movimento',
  '89 - Movimenti anormali',
  '90 - Farmaci del sistema nervoso e psicofarmaci',
  '91 - Tumori del sistema nervoso e delle meningi',
  '101 - Fisiologia respiratoria: ventilazione e circolazione polmonare, scambi gassosi',
  "102 - Infezioni dell'apparato respiratorio inferiore: Polmoniti comunitarie e forme cliniche peculiari, polmoniti nosocomiali, polmoniti nell'ospite immunocompromesso, polmoniti micotiche e parassitarie",
  '103 - Bronchiectasie e bronchiolite',
  '104 - Insufficienza respiratoria, Sindrome da distress respiratorio acuto (ARDS) e Alveolite emorragica',
  '105 - Disturbi della ventilazione: sindromi da ipo/iperventilazione',
  '106 - Sindrome delle apnee ostruttive del sonno (OSAS)',
  '107 - Pneumotorace',
  '108 - Versamento pleurico',
  '109 - Interstiziopatie polmonari: idiopatiche, da farmaci, associate a malattie del collagene, istiocitosi polmonare, Linfangioleiomiomatosi, Proteinosi alveolare',
  '110 - Sarcoidosi',
  '111 - Broncopneumopatia cronica ostruttiva (BPCO)',
  '112 - Asma e pneumopatie eosinofile',
  '113 - Patologia del diaframma e del mediastino',
  "115 - Farmaci dell'apparato respiratorio",
  '116 - Tumori polmonari',
  '117 - Malformazioni toraco-polmonari',
  '118 - BPCO GOLD 2022',
  '131 - Fisiologia della gravidanza',
  '132 - Controllo del benessere fetale in gravidanza: profilo biofisico, tocografia, farmaci, infezioni, radiazioni. Diagnosi prenatale',
  '133 - Complicanze della gravidanza: emorragie del primo secondo e terzo trimestre, aborto, malattia trofoblastica, placenta previa, distacco intempestivo di placenta, incompetenza cervicale, distacco di placenta, rottura vasa praevia, rottura utero',
  '134 - Gravidanza extrauterina',
  '135 - Parto fisiologico: induzione, espulsione placentare e post-parto',
  '136 - Parto prematuro e ritardo di crescita intrauterino (IUGR)',
  '137 - Patologie del post partum e del puerperio: emorragie post partum, inversione uterina, endometrite, febbre puerperale',
  '138 - Allattamento materno',
  '139 - Nutrizione e gravidanza',
  '140 - Sterilità ed infertilità femminile',
  '141 - Procreazione assistita',
  '142 - Contraccezione',
  "143 - Ciclo ovarico e mestruale e sue anomalie: endometriosi, sindrome dell'ovaio policistico, amenorree e meno/metrorragie",
  '144 - Menopausa e andropausa',
  '145 - Sanguinamento uterino anomalo: miomi, polipi, iperplasia endometriale',
  '146 - Prolasso uterino',
  '147 - Lesioni vulvari: Condilomi acuminati, tumori vulvari, Paget vulvare',
  '148 - Vulvovaginiti e malattia infiammatoria pelvica',
  '149 - Malattie infettive in gravidanza e infezioni urinarie gravidanza. ToRCH e vaccini',
  '150 - Infezioni prenatali ( congenite), neonatali e perineonatali.',
  '151 - Ipertensione in gravidanza, pre-eclampsia,eclampsia, sindrome HELLP',
  "152 - Tumori della cervice uterina e Tumori del corpo dell'utero",
  "153 - Tumori dell'ovaio",
  '154 - Tumori della mammella',
  "155 - Farmaci dell'apparato genitourinario",
  '156 - Amenorrea',
  '171 - Neonatologia: assistenza in sala parto,rianimazione, classificazione e esame obiettivo del neonato, alterazioni nel passaggio alla vita uterina, problemi associati a parti traumatici',
  '172 - Malattie respiratorie neonatali: apnea del prematuro, displasia broncopolmonare, sindrome da aspirazione di meconio, ipertensione polmonare persistente, tachipnea transitoria, sindrome da distress respiratorio del neonato, pneumotorace, pneumomediastino, enfisema polmonare, ernie diaframmatiche',
  "173 - Malattie dell' apparato digerente neonatali: ittero neonatale,iperbilirubinemia,enterocolite necrotizzante, Malattia di Hirschprung, occlusione intestinale, ileo da meconio, epatite neonatale, atresia biliare",
  '174 - Malattie ematologiche neonatali: anemia neonatale, malattia emolitica del neonato, policitemia, malattia emorragica del neonato, trombocitopenia neonatale',
  '175 - Encefalopatia ipossico ischemica e lesioni correlate',
  '176 - Patologia del cordone ombelicale: persistenza uraco, persistenza condotto onfalomesenterico, granuloma ombelicale, onfalite. Difetti della parete addominale: ernia ombelicale, onfalocele, gastroschisi',
  '177 - Malattie metaboliche del neonato: ipocalcemia e ipercalcemia, osteopenia del prematuro, figli di madri diabetiche, ipotiroidismo congenito, ipoglicemia',
  '178 - Vaccinazioni',
  '179 - Screening neonatali e nel bambino (anomalie ortopediche, disturbi visivi e uditivi). Mortalità e morbidità infantile',
  "180 - Esantemi e malattie infettive tipiche dell'infanzia: morbillo, rosolia, varicella, parvovirus B19, parotite, roseola infantum, scarlattina, malattia mani-piedi-bocca, esantemi da adenovirus, pertosse, difterite",
  '181 - Crescita e sviluppo normale e patologico.Alterazioni staturali',
  '182 - Pubertà normale e patologica',
  '183 - Nutrizione, malnutrizione e obesità del lattante e del bambino. Disidratazione.',
  '184 - Cardiopatie congenite',
  "185 - Malattie dell'apparato respiratorio pediatriche: ostruzione acuta delle vie respiratorie superiori, stridore laringeo, bronchiolite acute, bronchiolite obliterante, fibrosi cistica",
  "186 - Malattie dell'apparato digerente pediatriche: atresia e fistola tracheo-esofagea, stenosi ipertrofica del piloro, invaginazione intestinale, diverticolo di Meckel, disturbi della motilità intestinale, allergie alimentari, diarrea, disturbi funzionali gastrointestinali, malattia celiaca",
  '187 - Malattie nefrourologiche pediatriche: infezioni delle vie urinarie, reflusso vescico-ureterale e nefropatia da reflusso, malformazioni uro-genitali',
  '188 - Onco-ematologia pediatrica',
  '189 - Sincope e morte improvvisa del lattante',
  '190 - Maltrattamento infantile',
  '191 - Malattie genetiche e sindromi su base eredo-familiare',
  '200 - Dislipidemie',
  "201 - Diabete mellito di tipo 1 e 2 nel bambino e nell'adulto. Complicanze",
  '202 - Ipoglicemia',
  '204 - Obesità,sindrome metabolica, denutrizione, deficit vitaminici e nutrizione fisiologica',
  '205 - Gozzo e cenni di chirurgia tiroidea',
  '206 - Tiroiditi',
  '207 - Noduli tiroidei',
  '208 - Ipotiroidismo',
  '209 - Ipertiroidismo',
  '210 - Tumori della tiroide',
  '211 - Disturbi del metabolismo fosfocalcico ( iper e ipoparatiroidismo; pseudoipoparatiroidismo)',
  "213 - Patologie dell'asse ipotalamo-ipofisi (Adenoma ipofisario, SIADH, diabete insipido)",
  '213 - Osteoporosi e malattie metaboliche osso ( osteomalacia, rachitismo, malattia di Paget)',
  '214 - Ipogonadismo',
  '215 - Sindrome di Cushing, feocromocitoma, incidentaloma, iperaldosteronismo',
  '216 - Insufficienza surrenalica',
  '217 - Ginecomastia',
  '218 - Ateroma: epidemiologia e fisiopatologia. La malattia ateromasica polidistrettuale',
  '218 - Disturbi endocrini multipli: MEN e PGA',
  '219 - Farmaci del metabolismo e del sistema endocrino',
  "231 - Disturbi dell'equilibrio acido- base e disturbi idroelettrolitici",
  '233 - Sindrome nefritica',
  '234 - Nefropatie glomerulari',
  '235 - Nefropatie tubulari e intersitiziali:nefriti tubulo interstiziali e nefropatia ostruttiva',
  '236 - Nefropatie vascolari:nefropatia ischemica, ipertensione nefrovascolare, malattia ateroembolica renale, trombosi della vena renale',
  '237 - Insufficienza renale acuta ( Acute Kidney Injury)',
  '238 - Insufficienza renale cronica ( Chronic Kidney Disease )',
  '239 - Microangiopatie trombotiche',
  '240 - Tubulopatie ereditarie',
  '241 - Malformazioni renali e patologie renali ereditarie. Malattia del rene policistico.',
  '243 - Patologie renali con coinvolgimento di altri organi: sindrome cardio-renale, sindrome epato-renale, sindrome pulmo-renale',
  '244 - Dialisi',
  '245 - Infertilità maschile e varicocele',
  '246 - Patologia genito-scrotale (criptorchidismo, idrocele, fimosi, torsione di funicolo) e malformazioni urogenitali',
  "247 - Disfunzione sessuale nell'uomo: disfunzione erettile, malattia di La Peyronie, Eiaculazione precoce, Priapismo",
  '248 - Incontinenza urinaria e disturbi della minzione',
  '249 - Ipertrofia prostatica benigna e altre cause di ostruzione delle basse vie urinarie',
  '250 - Infezioni delle alte e basse vie urinarie. Cistiti e prostatiti',
  '251 - Ematuria',
  '252 - Litiasi urinaria',
  '253 - Andropausa',
  '254 - Trapianto di rene',
  '255 - Tumori renali',
  '256 - Tumori della vescica e delle alte vie escretrici',
  '258 - Tumori del testicolo',
  '259 - Tumori della prostata',
  '259 - Tumori del pene',
  '260 - Traumi Urologici',
  "270 - Emopoiesi e fisiologia dell'Emostasi",
  '271 - Anemia: sideropenica, da malattia cronica, megaloblastica, emolitica, mielftotisica',
  '273 - Emocromo: indicazioni e interpretazione',
  '274 - Patologia del ferro: emocromatosi',
  '275 - Disturbi della coagulazione: Emofilia, deficit di fattori della coagulazione, CID, patologie congenite protrombotiche',
  "276 - Piastrinopatie: Trombocitopenia, Trombocipatie e Malattie dell'emostasi primaria",
  '277 - Leucemie acute',
  '278 - Tricoleucemia o leucemia a cellule capellute',
  '279 - Leucemia linfatica cronica',
  '280 - Linfomi Hodgkin e non Hodgkin',
  '281 - Mieloma multiplo, MGUS e altre patologie delle plasmacellule',
  '282 - Sindromi mielodisplastiche',
  '283 - Sindromi Mieloproliferative Croniche: policitemia vera, mielofibrosi, trombocitemia essenziale, LMC',
  '284 - Eosinofilia primaria e secondaria',
  '285 - Splenomegalia: congestizia, Infettiva e infiammatoria, Mieloproliferativa e linfoproliferativa, da accumulo e strutturale',
  '286 - Trasfusioni di sangue e derivati dal sangue: indicazioni, complicanze. Emovigilanza',
  '287 - Trapianto di cellule staminali ematopoietiche',
  '288 - Patologia dei linfatici ( linfedema, linfangite)',
  '289 - Farmaci del sangue e degli organi ematopoietici',
  '289 - Tumori del timo e della milza',
  '301 - Fratture: principi generali e complicazioni',
  '302 - Protesi e osteosintesi',
  '303 - Lesioni periarticolari e legamentose del ginocchio, della caviglia e della spalla. Lussazioni e tendiniti.',
  '304 - Lesioni ligamentose della mano e patologia infiammatoria: de Quervain, Dupuytren',
  '305 - Sindrome dolorosa regionale complessa (es: algodistrofia di sudeck)',
  '306 - Lesioni del sistema nervoso periferico: sindromi da compressione nervosa, tunnel carpale',
  "307 - Infezioni dell'apparato osteoarticolomuscolare ( Miositi, Trichinellosi, Mialgia epidemica, Osteomieliti)",
  '308 - Patologie del rachide: Dolore lombare, Lombosciatalgia, Ernia del disco, Stenosi del canale lombare, Spondilolistesi, Siringomelia',
  '309 - Traumatologia della colonna vertebrale: fratture, scoliosi, spondilolistesi',
  "310 - Ortopedia infantile: displasia congenita dell'anca, legg-calvè-perthes, epifisiolisi, piede torto congenito, osteocondrosi",
  '311 - Tumori delle ossa',
  '321 - Reazione infiammatoria: aspetti biologici e clinici. Gestione - principali meccanismi',
  '322 - Artrosi e versamento articolare',
  '323 - Artrite reumatoide',
  '324 - Artriti microcristalline: gotta e iperuricemia, artrite da pirofosfato di calcio',
  '325 - Spondiloartriti: anchilosante, reattiva, psoriasica, associate ad IBD',
  '326 - Lupus eritematoso sistemico. Sindrome da anticorpi anti-fosfolipidi',
  '327 - Sclerosi sistemica',
  '328 - Polimialgia reumatica',
  '329 - Fibromialgia',
  '330 - Sindrome di Sjogren',
  '331 - Polimiosite-Dermatomiosite',
  '332 - Connettivite mista',
  '333 - Vasculiti: Behçet, Horton, Takayasu, Poliarterite nodosa, crioglobulinemica, Leucocitoclastica, Churg-Strauss, Wegener, Porpora di Henoch-Schönlein, Poliangioite microscopica,',
  '334 - Amiloidosi e sindromi autoinfiammatorie. Febbri periodiche',
  '335 - Farmaci del sistema immunitario: immunomodulatori e immunosoppressori',
  '341 - Anatomia e fisiologia della cute. Lesioni elementari e semeiotica dermatologica',
  '342 - Dermatosi immunomediate ( dermatosi bollose, dermatiti, connettiviti e vasculiti cutanee)',
  '343 - Orticaria,angioedema, dermatite atopica e da contatto',
  '344 - Acne, Rosacea, Dermatite seborroica',
  '345 - Psoriasi',
  '346 - Malattie cutanee genetiche: facomatosi',
  '347 - Discromie cutanee, Eczema, Alterazioni della cheratinizzazione',
  '348 - Emangiomi e malformazioni cutanee vascolari',
  '350 - Ulcerazioni cutanee croniche',
  '351 - Dermatosi da artropodi, protozoi, miceti, virus ( tra cui scabbia, pediculosi, leishmaniosi e malattie da herpes virus)',
  '352 - Patologie mucocutanee e degli annessi cutanei( capelli, peli, ghiandole, unghie). Micosi superficiali: tigne, candidosi, sporotricosi e altre. Elmintiasi tegumentarie: filariosi, dracunculosi, larva migrans cutanea, dirofilariosi.',
  '353 - Acrosindromi vascolari (fenomeno di Raynaud, eritromelalgia, acrocianosi, geloni, ischemia digitale)',
  '354 - Infezioni dei tessuti molli e delle fasce connettivali. Infezioni cutanee da streptococchi e stafilococchi, carbonchio, SSST, Erisipela, Cellulite e gangrena, Fascite necrotizzante, Treponematosi non veneree',
  '355 - Nevi',
  '356 - Alopecia',
  '357 - Lesioni cutanee correlate a malattie sistemiche',
  '358 - Tumori cutanei epiteliali e melanomi. Linfomi cutanei. Lesioni precancerose',
  '359 - Tumori delle parti molli',
  '360 - Gestione ferite',
  '371 - Generalità su agenti infettivi e diagnosi microbiologica',
  '372 - Febbre, febbre persistente, febbre negli immunodepressi, febbre di ritorno da viaggi in paesi tropicali',
  '373 - Infezioni da HIV e altri retrovirus',
  '374 - Malaria',
  '375 - Tubercolosi e micobatteriosi non tubercolari. Lebbra',
  '377 - Sepsi e batteriemia',
  '378 - Rickettsiosi esantematiche, ehrlichiosi e anaplasmosi. Infezioni trasmesse da artropodi: zecche, pidocchi, pulci, cimici,glossine, tabanidi,simulidi, ceratopogonidi)',
  '379 - Febbri emorragiche virali e infezioni trasmesse da zanzare',
  '380 - Infezioni trasmesse da animali domestici: psittacosi, toxocariasi. Infezioni conseguenti a morsi di animali domestici',
  '381 - Zoonosi',
  '382 - Malattie sessualmente trasmissibili: gonorrea e uretriti non gonococciche, clamidia, sifilide, HPV, tricomoniasi, linfogranuloma venereo, mollusco contagioso, granuloma inguinale, ulcera venerea',
  '383 - Infezioni da herpes virus',
  '384 - Infezioni dei pazienti immunocompromessi, trapiantati, diabetici, splenectomizzati, etilisti, tossicodipendenti, pazienti sottoposti a terapie con farmaci bioologici. Neutropenia febbrile',
  '385 - COVID-19',
  "386 - Infezioni nosocomiali e correlate all'assistenza",
  '387 - Antibiotici, antivirali e antifungini',
  '388 - Tetano',
  "388 - Infezioni dell'apparato emopoietico e del sistema linforeticolare: mononucleosi infettiva, brucellosi, citomegalovirus, leishmaniosi, peste, tularemia, malattia di lyme, toxoplasmosi,babesiosi, bartonellosi",
  '389 - Infezioni del fegato, delle vie biliari e delle ghiandole salivari: idatidosi, leptospirosi,shistosomiasi, fascioliasi, amebiasi, colecistite e colangite',
  "390 - Infezioni dell'apparato respiratorio superiore: Raffreddore comune, Infezioni della cavità orale e degli spazi fasciali profondi di testa e collo,Epiglottite, Laringite, Bronchite, Bronchiolite,Influenza",
  '391 - Rischio infettivo per i viaggiatori: febbre, diarrea del viaggiatore, manifestazioni dermatologiche, sindrome eosinofila, MTS, sindromi respiratorie, sindromi neurologiche',
  '392 - Rischi emergenti, bioterrorismo, malattie altamente trasmissibili',
  '401 - Tecniche di rianimazione (BLSD,ACLS, ventilazione)',
  '402 - Anestesia locale e generale. Bloccanti neuromuscolari. Ipertermia maligna',
  '403 - Valutazione anestesiologica e preparazione del paziente',
  '404 - Gestione delle vie aeree',
  '404 - Anestesia in gravidanza',
  '405 - Monitoraggio emodinamico. Accessi venosi centrali.',
  '406 - Ventilazione meccanica ( invasiva e non invasiva). Polmoniti associate a ventilatore',
  '407 - Fisiopatologia e terapia del dolore',
  '408 - Stato di shock. Principali eziologie: ipovolemico, settico, cardiogeno, anafilattico',
  '409 - Trauma cranico e maxillofacciale',
  '410 - Trauma maggiore (colonna vertebrale, torace, addome) e lesioni da agenti fisici (ustioni, ipo/ipertermia)',
  '411 - Gestione dei disastri (esplosioni, disastri chimici, radiazioni)',
  '412 - Cure palliative e paziente terminale',
  "421 - Anatomia e fisiologia dell'apparato visivo",
  '422 - Disturbi della rifrazione :ametropie, miopia, astigmatismo, ipermetropia',
  '423 - Strabismo e ambliopia',
  '424 - Patologia della retina (Distacco di retina, occlusione arteriosa/venosa retinica, retinopatia diabetica, ipertensiva, miopia degenerativa, etc)',
  '425 - Patologia del nervo ottico (Papilledema, Neurite ottica, Neuropatia ottica ischemica)',
  '426 - Patologia delle pupille (Pupilla di Marcus-Gunn, Argyll-Robertson, Adie, Sindrome di Horner)',
  '427 - Uveiti (anteriore, posteriore e tipiche)',
  '428 - Glaucoma (primario ad angolo aperto/chiuso e secondario)',
  '429 - Patologia della congiuntiva (congiuntivite infettiva, congiuntivite immunitaria)',
  '430 - Patologia della cornea (Cheratiti, Cheratopatie, Cheratocono, Distrofie corneali)',
  '431 - Patologia del cristallino (cataratta, lussazione del cristallino)',
  '432 - Patologia delle ghiandole lacrimali (Dacriocistite, cheratocongiutivite secca)',
  "433 - Patologia dell'orbita (Tromboflebite del seno cavernoso, Fistola carotidocavernosa, Emorragia orbitaria, Tumori orbitari, Pseudotumor inflamatorio)",
  '434 - Patologia delle palpebre',
  '435 - Oncologia Oculare (Melanoma della coroide, Tumori orbitari, Tumori della congiutiva, Retinoblastoma)',
  '436 - Laser in Oftalmologia',
  '441 - Semeiotica e diagnostica in otorinolaringoiatria e audiologia',
  "442 - Patologia dell'orecchio esterno: padiglione e CUE",
  "443 - Patologia dell'orecchio medio: otosclerosi, timpanosclerosi, patologia traumatica, patologia tumorale e otiti non infettive",
  "444 - Patologie dell'orecchio interno: presbiacusia, ipoacusia",
  '445 - Otiti esterna, media ed interna',
  '446 - Riniti e rinosinusiti e altre patologie non infettive di naso e seni paranasali',
  '447 - Patologia della faringe: faringiti, faringo-tonsilliti, tonsilliti, adenoiditi e ipertrofie tonsillari, angina faringea',
  '448 - Vertigini: labirintiti, vertigine parossistica posizionale benigna, Sindrome di Meniere, neuronite vestibolare',
  '449 - Epistassi, corpo estraneo intranasale, patologia traumatica nasofaciale',
  '450 - Patologia della laringe: Disfonia, patologia delle corde vocali, laringiti',
  '451 - Patologia delle ghiandole salivari neoplastica e non neoplastica',
  '452 - Farmaci degli organi di senso',
  '452 - Tumori della cavità orale, nasosinusale e rinofaringea e delle vie aerodigestive superiori',
  '461 - Misure in epidemiologia',
  '462 - Studi epidemiologici: tipi ed errori',
  '464 - Statistica descrittiva',
  '464 - Inferenza statistica',
  "465 - Verifica d'ipotesi",
  '466 - Probabilità',
  '467 - Studi di valutazione di un esame diagnostico',
  '468 - Salute pubblica ( tipologie di sistema sanitario , organizzazione sanitaria, legislazione sanitaria )',
  '469 - Sorveglianza delle malattie infettive trasmissibili',
  '470 - Igiene degli alimenti ( tossinfezione alimentare, malattie trasmesse dagli alimenti, contaminazione alimentare)',
  '471 - Principi di epidemiologia delle malattie infettive, delle malattie cronico degenerative e della disabilità',
  '472 - Promozione della salute, prevenzione delle malattie infettive e cronico-degenerative, fattori determinanti della salute',
  '474 - Ambiente e salute',
  '477 - Stili di vita e salute',
  '481 - Medicina legale generale, semeiotica e metodologia',
  '482 - Medicina legale penalistica',
  '483 - Medicina legale civilistica',
  '484 - Asfissiologia',
  '485 - Tanatologia, sopralluogo, identificazione',
  '486 - Deontologia e etica medica',
  '487 - Sistema sanitario nazionale',
  '488 - Previdenza sociale, sicurezza sociale, pensioni e assicurazioni',
  '489 - Traumatologia (lesioni da sforzo, arma bianca, corpi contundenti, arma da fuoco, grandi traumatismi, incidenti stradali, agenti fisici)',
  '490 - Interruzione volontaria di gravidanza (IVG)',
  '491 - La persona disabile: aspetti medico-legali',
  '492 - Violenza sessuale',
  '496 - Sicurezza sul lavoro:Decreto legislativo 81 del 9 aprile 2008',
  '497 - Rumore',
  '498 - Vibrazioni',
  '499 - Radiazioni ionizzanti',
  '500 - Lavoro al videoterminale',
  '501 - Consumo di alcool e stupefacenti in ambito lavorativo',
  '502 - Lavoro in agricoltura',
  '503 - Lavoro in sanità',
  '504 - Lavoro notturno e a turni',
  '505 - Patologia da metalli e solventi',
  '506 - Pneumopatie professionali, pneumoconiosi',
  '507 - Infezioni e vaccinazioni in ambito lavorativo',
  '508 - Incidenti sul lavoro e malattie professionali. Sistemi assicurativi per i lavoratori',
  '509 - Disturbi muscoloscheletrici e lavoro',
  '521 - Semeiotica psicopatologica',
  "522 - Classificazione dei disturbi mentali dal bambino all' anziano (DSM-5) e test psicometrici",
  '523 - Organizzazione dipartimento salute mentale. ASO e TSO.',
  '524 - Disturbi psichici: fattori di rischio, screening, prevenzione',
  '525 - Disturbi neurocognitivi: delirium, disturbi mnesici, pseudodemenze. Stato confusionale e alterazioni dello stato di coscienza',
  "526 - Disturbi del neurosviluppo: autismo, ADHD, tic, disabilità intellettiva, disturbi dell'apprendimento",
  "527 - Disturbi d'ansia: disturbo d'ansia generalizzato, disturbo di panico,attacco di panico, disturbo fobico, disturbo ossessivo compulsivo, disturbo da stress post traumatico)",
  "528 - Disturbi dell'umore (disturbo bipolare e disturbo depressivo, lutto e suicidio)",
  '529 - Disturbi dello spettro della schizofrenia e altri disturbi psicotici',
  '530 - Disturbi correlati a sostanze e disturbi da addiction',
  '531 - Disturbi del comportamento alimentare ( anoressia, bulimia)',
  '532 - Disturbi somatoformi',
  '533 - Disturbi del ciclo sonno-veglia',
  '534 - Disturbi di personalità',
  '535 - Disturbi dissociativi e fittizi',
  '536 - Disfunzioni sessuali, disforia di genere e disturbi parafilici',
  '537 - Disturbi psichici della gravidanza e del post-parto',
  "538 - Disturbi dell'evacuazione e della minzione in ambito psichiatrico. Enuresi ed encopresi",
  '539 - Disturbi da comportamento dirompente, controllo degli impulsi e della condotta',
  '551 - Concetti di diagnostica per immagini',
  '552 - Radiologia toracica',
  '553 - Radiologia addominale',
  '554 - Neuroradiologia',
  '555 - Radiologia muscoloscheletrica',
  '556 - Radiologia ginecologica',
  '561 - AP - Linfonodi',
  '562 - AP - Milza',
  '563 - AP - Timo',
  '564 - AP - Midollo emopoietico',
  '565 - AP - Cuore',
  '566 - AP - Vasi',
  '567 - AP - Testa-collo',
  '568 - AP - Polmone e pleura',
  '569 - AP - Apparato gastroenterico',
  '570 - AP - Fegato e vie biliari',
  '571 - AP - Pancreas',
  '572 - AP - Apparato endocrino',
  '573 - AP - Rene e vie urinarie',
  '574 - AP - Apparato genitale maschile',
  '575 - AP - Apparato genitale femminile',
  '576 - AP - Mammella',
  '577 - AP - Sistema nervoso periferico e muscolo scheletrico',
  '578 - AP - Scheletro e tessuti molli',
  '579 - AP - Sistema nervoso centrale',
  '591 - Epidemiologia, fattori di rischio, prevenzione e screening dei tumori',
  '593 - Diagnosi di neoplasia: segni di allarme e esami di laboratorio; stadiazione ; prognosi',
  "594 - Trattamento dei tumori: chirurgia, radioterapia, trattamenti medici(chemioterapia, terapie mirate, immunoterapia). La decisione terapeutica multidisciplinare e l'informazione del paziente",
  '595 - Gestione e supporto di un paziente oncologico in tutte le fasi della malattia, compresa la fase di cure palliative, affrontando questioni tecniche, relazionali, sociali ed etiche. Trattamenti sintomatici. Modalità di monitoraggio',
  '596 - Emergenze-urgenze in oncologia medica ( sindrome della vena cava superiore, sindrome da compressione midollare, neutropenia febbrile, sindrome da lisi tumorale)',
  '598 - Sindromi paraneoplastiche',
  '599 - Prime linee di trattamento in oncologia:speciale SSM 2022',
  '600 - Antineoplastici tradizionali, farmaci a bersaglio molecolare, farmaci biologici, terapia ormonale, immunoterapici',
  '601 - Cardioncologia',
  '621 - Farmacologia generale: definizioni, vie di somministrazione, assorbimento, distribuzione, metabolismo, eliminazione, concetti di farmacocinetica, interazion farmacologiche',
  '622 - Farmaci antinfiammatori non steroidei (FANS) e steroidei, oppioidi. Autacoidi ( istamina, prostaglandine)',
  '623 - Farmaci che agiscono sul simpatico e parasimpatico: colinergici, anticolinergici, adrenergici, antiadrenergici.',
  '624 - Intossicazioni e principi di tossicologia. Antidotismo',
  '625 - Farmaci approvati da FDA',
  '641 - Vecchiaia, senescenza, esame obiettivo del paziente anziano',
  '642 - Patologie e sindromi del paziente anziano',
  "643 - Complicazioni dell'immobilità e delle lesioni da decubito. Prevenzione e trattamento",
  '651 - Allergie e ipersensibilità',
  '652 - Immunodeficienze',
  '661 - Malformazioni cranio-maxillo-faciali',
  '662 - Traumatologia maxillo-faciale',
  '663 - Patologia cistica maxillo-faciale',
  '664 - Neoplasie delle ossa mascellari (tumori odontogeni e non odontogeni)',
  '665 - Patologia articolazione temporo-mandibolare e osteonecrosi della mandibola',
  '666 - Patologie benigne dei denti e del cavo orale',
]

const disciplinesItemsMap = {
  'Allergologia e immunologia clinica': ['651 - Allergie e ipersensibilità', '652 - Immunodeficienze'],
  'Anatomia patologica': [
    '561 - AP - Linfonodi',
    '562 - AP - Milza',
    '563 - AP - Timo',
    '564 - AP - Midollo emopoietico',
    '565 - AP - Cuore',
    '566 - AP - Vasi',
    '567 - AP - Testa-collo',
    '568 - AP - Polmone e pleura',
    '569 - AP - Apparato gastroenterico',
    '570 - AP - Fegato e vie biliari',
    '571 - AP - Pancreas',
    '572 - AP - Apparato endocrino',
    '573 - AP - Rene e vie urinarie',
    '574 - AP - Apparato genitale maschile',
    '575 - AP - Apparato genitale femminile',
    '576 - AP - Mammella',
    '577 - AP - Sistema nervoso periferico e muscolo scheletrico',
    '578 - AP - Scheletro e tessuti molli',
    '579 - AP - Sistema nervoso centrale',
  ],
  'Anestesia, Rianimazione e Emergenze': [
    "231 - Disturbi dell'equilibrio acido- base e disturbi idroelettrolitici",
    '401 - Tecniche di rianimazione (BLSD,ACLS, ventilazione)',
    '402 - Anestesia locale e generale. Bloccanti neuromuscolari. Ipertermia maligna',
    '403 - Valutazione anestesiologica e preparazione del paziente',
    '404 - Gestione delle vie aeree',
    '404 - Anestesia in gravidanza',
    '405 - Monitoraggio emodinamico. Accessi venosi centrali.',
    '406 - Ventilazione meccanica ( invasiva e non invasiva). Polmoniti associate a ventilatore',
    '407 - Fisiopatologia e terapia del dolore',
    '408 - Stato di shock. Principali eziologie: ipovolemico, settico, cardiogeno, anafilattico',
    '409 - Trauma cranico e maxillofacciale',
    '410 - Trauma maggiore (colonna vertebrale, torace, addome) e lesioni da agenti fisici (ustioni, ipo/ipertermia)',
    '411 - Gestione dei disastri (esplosioni, disastri chimici, radiazioni)',
    '412 - Cure palliative e paziente terminale',
  ],
  'Cardiologia, Cardiochirurgia e Chirurgia vascolare': [
    '1 - Semeiotica cardiovascolare',
    '2 - Fattori di rischio cardiovascolare e prevenzione',
    '3 - Cardiopatia ischemica: angina pectoris e infarto del miocardio',
    '4 - Valvulopatie',
    "6 - Patologie dell'aorta (aneurismi e dissezione aortica) e malattie obliteranti dei vasi periferici (AOAI)",
    '7 - Aritmie cardiache',
    '8 - Fibrillazione atriale (FA)',
    '9 - Elettrocardiogramma',
    '10 - Cardiomiopatie',
    '11 - Miocarditi',
    '12 - Ipertensione arteriosa ed emergenze ipertensive',
    '13 - Ipertensione polmonare',
    '14 - Malattie del pericardio: pericardite e versamento pericardico',
    '15 - Scompenso cardiaco ed edema polmonare',
    '17 - Trombosi venosa profonda ed embolia polmonare',
    '18 - Insufficienza venosa cronica e altre patologie delle vene',
    '19 - Endocardite infettiva',
    '20 - Sincope',
    '21 - Valutazione preconcezionale',
    '22 - Farmaci del sistema cardiovascolare',
    '23 - Tumori cardiaci',
    '24 - Aneurisma aortico e malattie obliteranti dei vasi periferici',
    '25 - Dolore toracico acuto e cronico',
    '26 - Trapianto di cuore',
  ],
  'Chirurgia Generale': [
    '35 - Litiasi biliare o colelitiasi e sue complicanze (colecistite, colangite, coledocolitiasi)',
    '53 - Patologia perianale: emorroidi, ragadi, fistole, incontinenza',
    '58 - Peritoniti e infezioni addominali',
    '60 - Occlusione intestinale (ileo)',
    '61 - Anatomia addominale',
    '62 - Ernie della parete addominale ed inguinali',
    '64 - Addome acuto',
  ],
  'Chirurgia maxillo-facciale': [
    '661 - Malformazioni cranio-maxillo-faciali',
    '662 - Traumatologia maxillo-faciale',
    '663 - Patologia cistica maxillo-faciale',
    '664 - Neoplasie delle ossa mascellari (tumori odontogeni e non odontogeni)',
    '665 - Patologia articolazione temporo-mandibolare e osteonecrosi della mandibola',
    '666 - Patologie benigne dei denti e del cavo orale',
  ],

  'Dermatologia e Chirurgia plastica': [
    '341 - Anatomia e fisiologia della cute. Lesioni elementari e semeiotica dermatologica',
    '342 - Dermatosi immunomediate ( dermatosi bollose, dermatiti, connettiviti e vasculiti cutanee)',
    '343 - Orticaria,angioedema, dermatite atopica e da contatto',
    '344 - Acne, Rosacea, Dermatite seborroica',
    '345 - Psoriasi',
    '346 - Malattie cutanee genetiche: facomatosi',
    '347 - Discromie cutanee, Eczema, Alterazioni della cheratinizzazione',
    '348 - Emangiomi e malformazioni cutanee vascolari',
    '350 - Ulcerazioni cutanee croniche',
    '351 - Dermatosi da artropodi, protozoi, miceti, virus ( tra cui scabbia, pediculosi, leishmaniosi e malattie da herpes virus)',
    '352 - Patologie mucocutanee e degli annessi cutanei( capelli, peli, ghiandole, unghie). Micosi superficiali: tigne, candidosi, sporotricosi e altre. Elmintiasi tegumentarie: filariosi, dracunculosi, larva migrans cutanea, dirofilariosi.',
    '353 - Acrosindromi vascolari (fenomeno di Raynaud, eritromelalgia, acrocianosi, geloni, ischemia digitale)',
    '354 - Infezioni dei tessuti molli e delle fasce connettivali. Infezioni cutanee da streptococchi e stafilococchi, carbonchio, SSST, Erisipela, Cellulite e gangrena, Fascite necrotizzante, Treponematosi non veneree',
    '355 - Nevi',
    '356 - Alopecia',
    '357 - Lesioni cutanee correlate a malattie sistemiche',
    '358 - Tumori cutanei epiteliali e melanomi. Linfomi cutanei. Lesioni precancerose',
    '359 - Tumori delle parti molli',
    '360 - Gestione ferite',
  ],
  Ematologia: [
    "270 - Emopoiesi e fisiologia dell'Emostasi",
    '271 - Anemia: sideropenica, da malattia cronica, megaloblastica, emolitica, mielftotisica',
    '273 - Emocromo: indicazioni e interpretazione',
    '274 - Patologia del ferro: emocromatosi',
    '275 - Disturbi della coagulazione: Emofilia, deficit di fattori della coagulazione, CID, patologie congenite protrombotiche',
    "276 - Piastrinopatie: Trombocitopenia, Trombocipatie e Malattie dell'emostasi primaria",
    '277 - Leucemie acute',
    '278 - Tricoleucemia o leucemia a cellule capellute',
    '279 - Leucemia linfatica cronica',
    '280 - Linfomi Hodgkin e non Hodgkin',
    '281 - Mieloma multiplo, MGUS e altre patologie delle plasmacellule',
    '282 - Sindromi mielodisplastiche',
    '283 - Sindromi Mieloproliferative Croniche: policitemia vera, mielofibrosi, trombocitemia essenziale, LMC',
    '284 - Eosinofilia primaria e secondaria',
    '285 - Splenomegalia: congestizia, Infettiva e infiammatoria, Mieloproliferativa e linfoproliferativa, da accumulo e strutturale',
    '286 - Trasfusioni di sangue e derivati dal sangue: indicazioni, complicanze. Emovigilanza',
    '287 - Trapianto di cellule staminali ematopoietiche',
    '288 - Patologia dei linfatici ( linfedema, linfangite)',
    '289 - Farmaci del sangue e degli organi ematopoietici',
    '289 - Tumori del timo e della milza',
  ],

  Endocrinologia: [
    '191 - Malattie genetiche e sindromi su base eredo-familiare',
    '200 - Dislipidemie',
    "201 - Diabete mellito di tipo 1 e 2 nel bambino e nell'adulto. Complicanze",
    '202 - Ipoglicemia',
    '204 - Obesità,sindrome metabolica, denutrizione, deficit vitaminici e nutrizione fisiologica',
    '205 - Gozzo e cenni di chirurgia tiroidea',
    '206 - Tiroiditi',
    '207 - Noduli tiroidei',
    '208 - Ipotiroidismo',
    '209 - Ipertiroidismo',
    '210 - Tumori della tiroide',
    '211 - Disturbi del metabolismo fosfocalcico ( iper e ipoparatiroidismo; pseudoipoparatiroidismo)',
    "213 - Patologie dell'asse ipotalamo-ipofisi (Adenoma ipofisario, SIADH, diabete insipido)",
    '213 - Osteoporosi e malattie metaboliche osso ( osteomalacia, rachitismo, malattia di Paget)',
    '214 - Ipogonadismo',
    '215 - Sindrome di Cushing, feocromocitoma, incidentaloma, iperaldosteronismo',
    '216 - Insufficienza surrenalica',
    '217 - Ginecomastia',
    '218 - Ateroma: epidemiologia e fisiopatologia. La malattia ateromasica polidistrettuale',
    '218 - Disturbi endocrini multipli: MEN e PGA',
    '219 - Farmaci del metabolismo e del sistema endocrino',
  ],

  'Farmacologia e Tossicologia': [
    '90 - Farmaci del sistema nervoso e psicofarmaci',
    '335 - Farmaci del sistema immunitario: immunomodulatori e immunosoppressori',
    '387 - Antibiotici, antivirali e antifungini',
    '621 - Farmacologia generale: definizioni, vie di somministrazione, assorbimento, distribuzione, metabolismo, eliminazione, concetti di farmacocinetica, interazion farmacologiche',
    '622 - Farmaci antinfiammatori non steroidei (FANS) e steroidei, oppioidi. Autacoidi ( istamina, prostaglandine)',
    '623 - Farmaci che agiscono sul simpatico e parasimpatico: colinergici, anticolinergici, adrenergici, antiadrenergici.',
    '624 - Intossicazioni e principi di tossicologia. Antidotismo',
    '625 - Farmaci approvati da FDA',
  ],

  Gastroenterologia: [
    '31 - Ittero: alterazioni del metabolismo della bilirubina (gilbert) e colestasi croniche (CBP, CSP)',
    '32 - Epatiti virali, autoimmuni e da sostanze tossiche',
    '33 - Epatopatie metaboliche (wilson) ed epatomegalie',
    '34 - Cirrosi epatica e sue complicanze (ascite, ipertensione portale, PBS, encefalopatia epatica, sindrome epatorenale)',
    '36 - Tumori del fegato',
    '37 - Tumori delle vie biliari',
    '38 - Trapianto di fegato',
    "39 - Disfagia, disturbi motori dell'esofago (acalasia), esofagiti",
    '40 - Malattia da reflusso gastroesofageo ed ernia iatale',
    "41 - Tumori dell'esofago",
    '42 - Ulcera gastrica e duodenale. Gastrite acuta e cronica. Gastropatia.',
    '43 - Tumori dello stomaco',
    '44 - Pancreatite acuta',
    '45 - Pancreatite cronica',
    '46 - Tumori pancreatici',
    "47 - Infezioni dell'apparato digerente: enteriti infettive da batteri e virus e parassitosi intestinali: giardiasi, amebiasi, teniasi, ascaridiasi, ossiuriasi",
    "48 - Diarrea non infettiva, diarrea cronica e sindrome dell'intestino irritabile",
    '49 - Stipsi',
    '50 - Malattie Infiammatorie Croniche Intestinali (MICI)',
    '51 - Sindromi da malassorbimento: celiachia, whipple',
    '52 - Malattia diverticolare: diventicolosi e diverticolite',
    '54 - Appendicite',
    "55 - Tumori del colon-retto e dell'ano. Poliposi colon-rettali e condizioni eredo familiari predisponenti.",
    '56 - Sanguinamento gastrointestinale',
    '57 - Patologia vascolare intestinale: colite ischemica, ischemia mesenterica',
    '59 - Ascite',
    '63 - Vomito',
    '65 - GIST e NET ',
    "66 - Farmaci dell'apparato digerente",
  ],

  Geriatria: [
    '641 - Vecchiaia, senescenza, esame obiettivo del paziente anziano',
    '642 - Patologie e sindromi del paziente anziano',
    "643 - Complicazioni dell'immobilità e delle lesioni da decubito. Prevenzione e trattamento",
  ],

  'Ginecologia e ostetricia': [
    '131 - Fisiologia della gravidanza',
    '132 - Controllo del benessere fetale in gravidanza: profilo biofisico, tocografia, farmaci, infezioni, radiazioni. Diagnosi prenatale',
    '133 - Complicanze della gravidanza: emorragie del primo secondo e terzo trimestre, aborto, malattia trofoblastica, placenta previa, distacco intempestivo di placenta, incompetenza cervicale, distacco di placenta, rottura vasa praevia, rottura utero',
    '134 - Gravidanza extrauterina',
    '135 - Parto fisiologico: induzione, espulsione placentare e post-parto',
    '136 - Parto prematuro e ritardo di crescita intrauterino (IUGR)',
    '137 - Patologie del post partum e del puerperio: emorragie post partum, inversione uterina, endometrite, febbre puerperale',
    '138 - Allattamento materno',
    '139 - Nutrizione e gravidanza',
    '140 - Sterilità ed infertilità femminile',
    '141 - Procreazione assistita',
    '142 - Contraccezione',
    "143 - Ciclo ovarico e mestruale e sue anomalie: endometriosi, sindrome dell'ovaio policistico, amenorree e meno/metrorragie",
    '144 - Menopausa e andropausa',
    '145 - Sanguinamento uterino anomalo: miomi, polipi, iperplasia endometriale',
    '146 - Prolasso uterino',
    '147 - Lesioni vulvari: Condilomi acuminati, tumori vulvari, Paget vulvare',
    '148 - Vulvovaginiti e malattia infiammatoria pelvica',
    '149 - Malattie infettive in gravidanza e infezioni urinarie gravidanza. ToRCH e vaccini',
    '150 - Infezioni prenatali ( congenite), neonatali e perineonatali.',
    '151 - Ipertensione in gravidanza, pre-eclampsia,eclampsia, sindrome HELLP',
    "152 - Tumori della cervice uterina e Tumori del corpo dell'utero",
    "153 - Tumori dell'ovaio",
    '154 - Tumori della mammella',
    "155 - Farmaci dell'apparato genitourinario",
    '156 - Amenorrea',
  ],

  'Igiene,medicina preventiva e statistica': [
    '461 - Misure in epidemiologia',
    '462 - Studi epidemiologici: tipi ed errori',
    '464 - Statistica descrittiva',
    '464 - Inferenza statistica',
    "465 - Verifica d'ipotesi",
    '466 - Probabilità',
    '467 - Studi di valutazione di un esame diagnostico',
    '468 - Salute pubblica ( tipologie di sistema sanitario , organizzazione sanitaria, legislazione sanitaria )',
    '469 - Sorveglianza delle malattie infettive trasmissibili',
    '470 - Igiene degli alimenti ( tossinfezione alimentare, malattie trasmesse dagli alimenti, contaminazione alimentare)',
    '471 - Principi di epidemiologia delle malattie infettive, delle malattie cronico degenerative e della disabilità',
    '472 - Promozione della salute, prevenzione delle malattie infettive e cronico-degenerative, fattori determinanti della salute',
    '474 - Ambiente e salute',
    '477 - Stili di vita e salute',
  ],

  'Malattie infettive': [
    '87 - Infezioni del sistema nervoso: meningiti, encefaliti, mieliti , neuriti, radicoliti, ascessi ,empiemi. Tetano e botulino. Malattie da prioni',
    "180 - Esantemi e malattie infettive tipiche dell'infanzia: morbillo, rosolia, varicella, parvovirus B19, parotite, roseola infantum, scarlattina, malattia mani-piedi-bocca, esantemi da adenovirus, pertosse, difterite",
    '371 - Generalità su agenti infettivi e diagnosi microbiologica',
    '372 - Febbre, febbre persistente, febbre negli immunodepressi, febbre di ritorno da viaggi in paesi tropicali',
    '373 - Infezioni da HIV e altri retrovirus',
    '374 - Malaria',
    '375 - Tubercolosi e micobatteriosi non tubercolari. Lebbra',
    '377 - Sepsi e batteriemia',
    '378 - Rickettsiosi esantematiche, ehrlichiosi e anaplasmosi. Infezioni trasmesse da artropodi: zecche, pidocchi, pulci, cimici,glossine, tabanidi,simulidi, ceratopogonidi)',
    '379 - Febbri emorragiche virali e infezioni trasmesse da zanzare',
    '380 - Infezioni trasmesse da animali domestici: psittacosi, toxocariasi. Infezioni conseguenti a morsi di animali domestici',
    '381 - Zoonosi',
    '382 - Malattie sessualmente trasmissibili: gonorrea e uretriti non gonococciche, clamidia, sifilide, HPV, tricomoniasi, linfogranuloma venereo, mollusco contagioso, granuloma inguinale, ulcera venerea',
    '383 - Infezioni da herpes virus',
    '384 - Infezioni dei pazienti immunocompromessi, trapiantati, diabetici, splenectomizzati, etilisti, tossicodipendenti, pazienti sottoposti a terapie con farmaci bioologici. Neutropenia febbrile',
    '385 - COVID-19',
    "386 - Infezioni nosocomiali e correlate all'assistenza",
    '388 - Tetano',
    "388 - Infezioni dell'apparato emopoietico e del sistema linforeticolare: mononucleosi infettiva, brucellosi, citomegalovirus, leishmaniosi, peste, tularemia, malattia di lyme, toxoplasmosi,babesiosi, bartonellosi",
    '389 - Infezioni del fegato, delle vie biliari e delle ghiandole salivari: idatidosi, leptospirosi,shistosomiasi, fascioliasi, amebiasi, colecistite e colangite',
    "390 - Infezioni dell'apparato respiratorio superiore: Raffreddore comune, Infezioni della cavità orale e degli spazi fasciali profondi di testa e collo,Epiglottite, Laringite, Bronchite, Bronchiolite,Influenza",
    '391 - Rischio infettivo per i viaggiatori: febbre, diarrea del viaggiatore, manifestazioni dermatologiche, sindrome eosinofila, MTS, sindromi respiratorie, sindromi neurologiche',
    '392 - Rischi emergenti, bioterrorismo, malattie altamente trasmissibili',
  ],

  'Medicina del lavoro': [
    '496 - Sicurezza sul lavoro:Decreto legislativo 81 del 9 aprile 2008',
    '497 - Rumore',
    '498 - Vibrazioni',
    '499 - Radiazioni ionizzanti',
    '500 - Lavoro al videoterminale',
    '501 - Consumo di alcool e stupefacenti in ambito lavorativo',
    '502 - Lavoro in agricoltura',
    '503 - Lavoro in sanità',
    '504 - Lavoro notturno e a turni',
    '505 - Patologia da metalli e solventi',
    '506 - Pneumopatie professionali, pneumoconiosi',
    '507 - Infezioni e vaccinazioni in ambito lavorativo',
    '508 - Incidenti sul lavoro e malattie professionali. Sistemi assicurativi per i lavoratori',
    '509 - Disturbi muscoloscheletrici e lavoro',
  ],

  'Medicina legale': [
    '481 - Medicina legale generale, semeiotica e metodologia',
    '482 - Medicina legale penalistica',
    '483 - Medicina legale civilistica',
    '484 - Asfissiologia',
    '485 - Tanatologia, sopralluogo, identificazione',
    '486 - Deontologia e etica medica',
    '487 - Sistema sanitario nazionale',
    '488 - Previdenza sociale, sicurezza sociale, pensioni e assicurazioni',
    '489 - Traumatologia (lesioni da sforzo, arma bianca, corpi contundenti, arma da fuoco, grandi traumatismi, incidenti stradali, agenti fisici)',
    '490 - Interruzione volontaria di gravidanza (IVG)',
    '491 - La persona disabile: aspetti medico-legali',
    '492 - Violenza sessuale',
  ],

  Nefrologia: [
    '233 - Sindrome nefritica',
    '234 - Nefropatie glomerulari',
    '235 - Nefropatie tubulari e intersitiziali:nefriti tubulo interstiziali e nefropatia ostruttiva',
    '236 - Nefropatie vascolari:nefropatia ischemica, ipertensione nefrovascolare, malattia ateroembolica renale, trombosi della vena renale',
    '237 - Insufficienza renale acuta ( Acute Kidney Injury)',
    '238 - Insufficienza renale cronica ( Chronic Kidney Disease )',
    '239 - Microangiopatie trombotiche',
    '240 - Tubulopatie ereditarie',
    '241 - Malformazioni renali e patologie renali ereditarie. Malattia del rene policistico.',
    '243 - Patologie renali con coinvolgimento di altri organi: sindrome cardio-renale, sindrome epato-renale, sindrome pulmo-renale',
    '244 - Dialisi',
  ],
  Neurologia: [
    '71 - Anatomia, fisiologia e semeiotica neurologica',
    '72 - Paralisi facciale',
    '73 - Malattia vascolare cerebrale: TIA, ictus, emorragia intraparenchimale, MAV, trombosi dei seni venosi',
    '74 - Emorragia subdurale, subaracnoidea ed ematoma epidurale',
    '75 - Sclerosi multipla e altre malattie demielinizzanti',
    '76 - Sclerosi laterale amiotrofica e altre malattie del motoneurone',
    '77 - Miastenia e malattie della giunzione neuromuscolare',
    '78 - Neuropatie periferiche: polineuropatie, multineuropatie, poliradiculopatia, plessopatie, ganglionopatia, neuronopatia. Sindromi radicolari, plessuali e dei nervi periferici',
    '79 - Sindrome di Guillain-Barré',
    '80 - Cefalee: emicrania, cefalea muscolotensiva, cefalea autonomica e nevralgia del trigemino. Cefalee secondarie',
    '81 - Deficit motori e/o sensitivi degli arti, Miopatie e distrofie muscolari',
    '82 - Idrocefalo e ipertensione intracranica',
    '83 - Epilessia, crisi epilettiche e sindromi epilettiche. Convulsioni febbrili.',
    "84 - Disturbi della deambulazione e dell'equilibrio",
    '85 - Sindromi da compressione midollare non traumatica: sindrome della cauda equina, siringomielia',
    '86 - Coma e altri disturbi della coscienza. Morte cerebrale',
    '88 - Disturbi del movimento: Corea di Huntington, Parkinson e Parkinsonismi, Atassie e altri disturbi del movimento',
    '89 - Movimenti anormali',
    '91 - Tumori del sistema nervoso e delle meningi',
  ],

  Oculistica: [
    "421 - Anatomia e fisiologia dell'apparato visivo",
    '422 - Disturbi della rifrazione :ametropie, miopia, astigmatismo, ipermetropia',
    '423 - Strabismo e ambliopia',
    '424 - Patologia della retina (Distacco di retina, occlusione arteriosa/venosa retinica, retinopatia diabetica, ipertensiva, miopia degenerativa, etc)',
    '425 - Patologia del nervo ottico (Papilledema, Neurite ottica, Neuropatia ottica ischemica)',
    '426 - Patologia delle pupille (Pupilla di Marcus-Gunn, Argyll-Robertson, Adie, Sindrome di Horner)',
    '427 - Uveiti (anteriore, posteriore e tipiche)',
    '428 - Glaucoma (primario ad angolo aperto/chiuso e secondario)',
    '429 - Patologia della congiuntiva (congiuntivite infettiva, congiuntivite immunitaria)',
    '430 - Patologia della cornea (Cheratiti, Cheratopatie, Cheratocono, Distrofie corneali)',
    '431 - Patologia del cristallino (cataratta, lussazione del cristallino)',
    '432 - Patologia delle ghiandole lacrimali (Dacriocistite, cheratocongiutivite secca)',
    "433 - Patologia dell'orbita (Tromboflebite del seno cavernoso, Fistola carotidocavernosa, Emorragia orbitaria, Tumori orbitari, Pseudotumor inflamatorio)",
    '434 - Patologia delle palpebre',
    '435 - Oncologia Oculare (Melanoma della coroide, Tumori orbitari, Tumori della congiutiva, Retinoblastoma)',
    '436 - Laser in Oftalmologia',
  ],

  Oncologia: [
    '591 - Epidemiologia, fattori di rischio, prevenzione e screening dei tumori',
    '593 - Diagnosi di neoplasia: segni di allarme e esami di laboratorio; stadiazione ; prognosi',
    "594 - Trattamento dei tumori: chirurgia, radioterapia, trattamenti medici(chemioterapia, terapie mirate, immunoterapia). La decisione terapeutica multidisciplinare e l'informazione del paziente",
    '595 - Gestione e supporto di un paziente oncologico in tutte le fasi della malattia, compresa la fase di cure palliative, affrontando questioni tecniche, relazionali, sociali ed etiche. Trattamenti sintomatici. Modalità di monitoraggio',
    '596 - Emergenze-urgenze in oncologia medica ( sindrome della vena cava superiore, sindrome da compressione midollare, neutropenia febbrile, sindrome da lisi tumorale)',
    '598 - Sindromi paraneoplastiche',
    '599 - Prime linee di trattamento in oncologia:speciale SSM 2022',
    '600 - Antineoplastici tradizionali, farmaci a bersaglio molecolare, farmaci biologici, terapia ormonale, immunoterapici',
    '601 - Cardioncologia',
  ],

  Ortopedia: [
    '301 - Fratture: principi generali e complicazioni',
    '302 - Protesi e osteosintesi',
    '303 - Lesioni periarticolari e legamentose del ginocchio, della caviglia e della spalla. Lussazioni e tendiniti.',
    '304 - Lesioni ligamentose della mano e patologia infiammatoria: de Quervain, Dupuytren',
    '305 - Sindrome dolorosa regionale complessa (es: algodistrofia di sudeck)',
    '306 - Lesioni del sistema nervoso periferico: sindromi da compressione nervosa, tunnel carpale',
    "307 - Infezioni dell'apparato osteoarticolomuscolare ( Miositi, Trichinellosi, Mialgia epidemica, Osteomieliti)",
    '308 - Patologie del rachide: Dolore lombare, Lombosciatalgia, Ernia del disco, Stenosi del canale lombare, Spondilolistesi, Siringomelia',
    '309 - Traumatologia della colonna vertebrale: fratture, scoliosi, spondilolistesi',
    "310 - Ortopedia infantile: displasia congenita dell'anca, legg-calvè-perthes, epifisiolisi, piede torto congenito, osteocondrosi",
    '311 - Tumori delle ossa',
  ],

  Otorinolaringoiatria: [
    '441 - Semeiotica e diagnostica in otorinolaringoiatria e audiologia',
    "442 - Patologia dell'orecchio esterno: padiglione e CUE",
    "443 - Patologia dell'orecchio medio: otosclerosi, timpanosclerosi, patologia traumatica, patologia tumorale e otiti non infettive",
    "444 - Patologie dell'orecchio interno: presbiacusia, ipoacusia",
    '445 - Otiti esterna, media ed interna',
    '446 - Riniti e rinosinusiti e altre patologie non infettive di naso e seni paranasali',
    '447 - Patologia della faringe: faringiti, faringo-tonsilliti, tonsilliti, adenoiditi e ipertrofie tonsillari, angina faringea',
    '448 - Vertigini: labirintiti, vertigine parossistica posizionale benigna, Sindrome di Meniere, neuronite vestibolare',
    '449 - Epistassi, corpo estraneo intranasale, patologia traumatica nasofaciale',
    '450 - Patologia della laringe: Disfonia, patologia delle corde vocali, laringiti',
    '451 - Patologia delle ghiandole salivari neoplastica e non neoplastica',
    '452 - Farmaci degli organi di senso',
    '452 - Tumori della cavità orale, nasosinusale e rinofaringea e delle vie aerodigestive superiori',
  ],

  Pediatria: [
    '49 - Disturbi della minzione nei bambini',
    '171 - Neonatologia: assistenza in sala parto,rianimazione, classificazione e esame obiettivo del neonato, alterazioni nel passaggio alla vita uterina, problemi associati a parti traumatici',
    '172 - Malattie respiratorie neonatali: apnea del prematuro, displasia broncopolmonare, sindrome da aspirazione di meconio, ipertensione polmonare persistente, tachipnea transitoria, sindrome da distress respiratorio del neonato, pneumotorace, pneumomediastino, enfisema polmonare, ernie diaframmatiche',
    "173 - Malattie dell' apparato digerente neonatali: ittero neonatale,iperbilirubinemia,enterocolite necrotizzante, Malattia di Hirschprung, occlusione intestinale, ileo da meconio, epatite neonatale, atresia biliare",
    '174 - Malattie ematologiche neonatali: anemia neonatale, malattia emolitica del neonato, policitemia, malattia emorragica del neonato, trombocitopenia neonatale',
    '175 - Encefalopatia ipossico ischemica e lesioni correlate',
    '176 - Patologia del cordone ombelicale: persistenza uraco, persistenza condotto onfalomesenterico, granuloma ombelicale, onfalite. Difetti della parete addominale: ernia ombelicale, onfalocele, gastroschisi',
    '177 - Malattie metaboliche del neonato: ipocalcemia e ipercalcemia, osteopenia del prematuro, figli di madri diabetiche, ipotiroidismo congenito, ipoglicemia',
    '178 - Vaccinazioni',
    '179 - Screening neonatali e nel bambino (anomalie ortopediche, disturbi visivi e uditivi). Mortalità e morbidità infantile',
    '181 - Crescita e sviluppo normale e patologico.Alterazioni staturali',
    '182 - Pubertà normale e patologica',
    '183 - Nutrizione, malnutrizione e obesità del lattante e del bambino. Disidratazione.',
    '184 - Cardiopatie congenite',
    "185 - Malattie dell'apparato respiratorio pediatriche: ostruzione acuta delle vie respiratorie superiori, stridore laringeo, bronchiolite acute, bronchiolite obliterante, fibrosi cistica",
    "186 - Malattie dell'apparato digerente pediatriche: atresia e fistola tracheo-esofagea, stenosi ipertrofica del piloro, invaginazione intestinale, diverticolo di Meckel, disturbi della motilità intestinale, allergie alimentari, diarrea, disturbi funzionali gastrointestinali, malattia celiaca",
    '187 - Malattie nefrourologiche pediatriche: infezioni delle vie urinarie, reflusso vescico-ureterale e nefropatia da reflusso, malformazioni uro-genitali',
    '188 - Onco-ematologia pediatrica',
    '189 - Sincope e morte improvvisa del lattante',
    '190 - Maltrattamento infantile',
  ],

  Pneumologia: [
    '101 - Fisiologia respiratoria: ventilazione e circolazione polmonare, scambi gassosi',
    "102 - Infezioni dell'apparato respiratorio inferiore: Polmoniti comunitarie e forme cliniche peculiari, polmoniti nosocomiali, polmoniti nell'ospite immunocompromesso, polmoniti micotiche e parassitarie",
    '103 - Bronchiectasie e bronchiolite',
    '104 - Insufficienza respiratoria, Sindrome da distress respiratorio acuto (ARDS) e Alveolite emorragica',
    '105 - Disturbi della ventilazione: sindromi da ipo/iperventilazione',
    '106 - Sindrome delle apnee ostruttive del sonno (OSAS)',
    '107 - Pneumotorace',
    '108 - Versamento pleurico',
    '109 - Interstiziopatie polmonari: idiopatiche, da farmaci, associate a malattie del collagene, istiocitosi polmonare, Linfangioleiomiomatosi, Proteinosi alveolare',
    '110 - Sarcoidosi',
    '111 - Broncopneumopatia cronica ostruttiva (BPCO)',
    '112 - Asma e pneumopatie eosinofile',
    '113 - Patologia del diaframma e del mediastino',
    "115 - Farmaci dell'apparato respiratorio",
    '116 - Tumori polmonari',
    '117 - Malformazioni toraco-polmonari',
    '118 - BPCO GOLD 2022',
  ],

  Psichiatria: [
    '521 - Semeiotica psicopatologica',
    "522 - Classificazione dei disturbi mentali dal bambino all' anziano (DSM-5) e test psicometrici",
    '523 - Organizzazione dipartimento salute mentale. ASO e TSO.',
    '524 - Disturbi psichici: fattori di rischio, screening, prevenzione',
    '525 - Disturbi neurocognitivi: delirium, disturbi mnesici, pseudodemenze. Stato confusionale e alterazioni dello stato di coscienza',
    "526 - Disturbi del neurosviluppo: autismo, ADHD, tic, disabilità intellettiva, disturbi dell'apprendimento",
    "527 - Disturbi d'ansia: disturbo d'ansia generalizzato, disturbo di panico,attacco di panico, disturbo fobico, disturbo ossessivo compulsivo, disturbo da stress post traumatico)",
    "528 - Disturbi dell'umore (disturbo bipolare e disturbo depressivo, lutto e suicidio)",
    '529 - Disturbi dello spettro della schizofrenia e altri disturbi psicotici',
    '530 - Disturbi correlati a sostanze e disturbi da addiction',
    '531 - Disturbi del comportamento alimentare ( anoressia, bulimia)',
    '532 - Disturbi somatoformi',
    '533 - Disturbi del ciclo sonno-veglia',
    '534 - Disturbi di personalità',
    '535 - Disturbi dissociativi e fittizi',
    '536 - Disfunzioni sessuali, disforia di genere e disturbi parafilici',
    '537 - Disturbi psichici della gravidanza e del post-parto',
    "538 - Disturbi dell'evacuazione e della minzione in ambito psichiatrico. Enuresi ed encopresi",
    '539 - Disturbi da comportamento dirompente, controllo degli impulsi e della condotta',
  ],

  Radiodiagnostica: [
    '551 - Concetti di diagnostica per immagini',
    '552 - Radiologia toracica',
    '553 - Radiologia addominale',
    '554 - Neuroradiologia',
    '555 - Radiologia muscoloscheletrica',
    '556 - Radiologia ginecologica',
  ],

  Reumatologia: [
    '321 - Reazione infiammatoria: aspetti biologici e clinici. Gestione - principali meccanismi',
    '322 - Artrosi e versamento articolare',
    '323 - Artrite reumatoide',
    '324 - Artriti microcristalline: gotta e iperuricemia, artrite da pirofosfato di calcio',
    '325 - Spondiloartriti: anchilosante, reattiva, psoriasica, associate ad IBD',
    '326 - Lupus eritematoso sistemico. Sindrome da anticorpi anti-fosfolipidi',
    '327 - Sclerosi sistemica',
    '328 - Polimialgia reumatica',
    '329 - Fibromialgia',
    '330 - Sindrome di Sjogren',
    '331 - Polimiosite-Dermatomiosite',
    '332 - Connettivite mista',
    '333 - Vasculiti: Behçet, Horton, Takayasu, Poliarterite nodosa, crioglobulinemica, Leucocitoclastica, Churg-Strauss, Wegener, Porpora di Henoch-Schönlein, Poliangioite microscopica,',
    '334 - Amiloidosi e sindromi autoinfiammatorie. Febbri periodiche',
  ],

  Urologia: [
    '245 - Infertilità maschile e varicocele',
    '246 - Patologia genito-scrotale (criptorchidismo, idrocele, fimosi, torsione di funicolo) e malformazioni urogenitali',
    "247 - Disfunzione sessuale nell'uomo: disfunzione erettile, malattia di La Peyronie, Eiaculazione precoce, Priapismo",
    '248 - Incontinenza urinaria e disturbi della minzione',
    '249 - Ipertrofia prostatica benigna e altre cause di ostruzione delle basse vie urinarie',
    '250 - Infezioni delle alte e basse vie urinarie. Cistiti e prostatiti',
    '251 - Ematuria',
    '252 - Litiasi urinaria',
    '253 - Andropausa',
    '254 - Trapianto di rene',
    '255 - Tumori renali',
    '256 - Tumori della vescica e delle alte vie escretrici',
    '258 - Tumori del testicolo',
    '259 - Tumori della prostata',
    '259 - Tumori del pene',
    '260 - Traumi Urologici',
  ],
}

export const disciplines = Object.keys(disciplinesItemsMap)

export const itemsDisciplines = Object.entries(disciplinesItemsMap).reduce<Record<string, string[]>>(
  (finalMapping, [discipline, items]) => {
    items.forEach((item) => {
      if (!(item in finalMapping)) finalMapping[item] = []
      finalMapping[item].push(discipline)
    })
    return finalMapping
  },
  {}
)
